# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4682bab88a023023358fad5c93a86c6831a2994c1e6ddc6548b646f92e7cc22988c52ca30c7916d5c5f52a71d1f8618e4da33bcf3e32f5a8f5d2ba2dccddfb8

test:
  secret_key_base: 0b1350bf258017ff2dc7b6c04f087d3e679eea3b2d2c7f1b7ce30a6d244f1c5c9e0a81345e2a141ef1a7bae933f864f736473ac898a20062584e830a562fb420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
